# SPDX-License-Identifier: Apache-2.0
# Validated on one 80 GB H100: two same-GPU Fun-ASR-Nano replicas with shared
# weights.

config_cls: FunASRPipelineConfig
name: funasr
model_path: FunAudioLLM/Fun-ASR-Nano-2512-hf

stages:
  asr:
    engine:
      mem_fraction_static: 0.20
      max_total_tokens: 30000
