# SPDX-License-Identifier: Apache-2.0
# Validated on one 80 GB H100: two same-GPU MOSS Transcribe-Diarize replicas
# with shared weights.

config_cls: MossTranscribeDiarizePipelineConfig
name: mtd
model_path: OpenMOSS-Team/MOSS-Transcribe-Diarize

stages:
  asr:
    engine:
      mem_fraction_static: 0.20
      max_total_tokens: 40000
