# SPDX-License-Identifier: Apache-2.0
# Validated on one 80 GB H100: two same-GPU MOSS TTS local replicas with
# shared weights. Per-replica budget: AR 0.30 plus 0.15 codec reserve.

config_cls: MossTTSLocalPipelineConfig
name: mossl
model_path: OpenMOSS-Team/MOSS-TTS-Local-Transformer-v1.5

stages:
  tts_engine:
    gpu_memory_fraction: 0.45
    engine:
      mem_fraction_static: 0.30
      max_total_tokens: 30000
