# SPDX-License-Identifier: Apache-2.0
# BF16 colocated profile for the TTS CI stage (2 DP replicas behind the router).
config_cls: Qwen3OmniSpeechColocatedPipelineConfig
name: qwen3-omni-colocated-h100-bf16
model_path: Qwen/Qwen3-Omni-30B-A3B-Instruct

stages:
  image_encoder:
    gpu_memory_fraction: 0.02
  audio_encoder:
    gpu_memory_fraction: 0.02
  thinker:
    gpu_memory_fraction: 0.78
    engine:
      cuda_graph_backend_prefill: breakable
      cuda_graph_max_bs_prefill: 2048
  talker_ar:
    gpu_memory_fraction: 0.10
  code2wav:
    gpu_memory_fraction: 0.02
